# Generated by Django 5.0.6 on 2024-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_hospital_delete_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
