# Generated by Django 5.0.6 on 2024-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_patient_id_patient_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default={'form_2': []})),
            ],
        ),
        migrations.DeleteModel(
            name='PatientInfo',
        ),
    ]
